# Site settings
author: Christina
title: Coding! Easy, right?
header-img: img/home-bg.png
email: clhoward33@icloud.com
copyright_name: Christina
description: > # this means to ignore newlines until "baseurl:"
  Former free spirit, turned coder.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tiptoemosquito

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
